### ISSUE TITLE
xps13 9350 support

### ISSUE THREAD

**Issue by maz-1** [the-darkvoid/macOS-IOElectrify#4]
When I am explorering dsdt file from xps13 9350, I noticed that property _UID of device PNP0C14 is zero, what should I do in this case?
![1](https://user-images.githubusercontent.com/5277060/34196107-93faee0e-e59b-11e7-935a-98cadb43681a.JPG)

And here is the dsdt file
[DSDT.dsl.zip](https://github.com/the-darkvoid/macOS-IOElectrify/files/1574605/DSDT.dsl.zip)

**Comment by maz-1** [comment]
Also, I did't find "WTBT" in DSDT

**Comment by the-darkvoid** [comment]
It doesn't look like your laptop has Thunderbolt PNP.
It's only present in newer laptops.

**Comment by maz-1** [comment]
So what instead takes control of thunderbolt in this case?
xps 13 9350 do have thunderbolt 3 support anyway.
